// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.easy.ntprotocol.protobuf;

public final class ChatBuf {
  private ChatBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userNo = 1;
    /**
     * <code>required string userNo = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    boolean hasUserNo();
    /**
     * <code>required string userNo = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    java.lang.String getUserNo();
    /**
     * <code>required string userNo = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNoBytes();

    // required string friendNo = 2;
    /**
     * <code>required string friendNo = 2;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    boolean hasFriendNo();
    /**
     * <code>required string friendNo = 2;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    java.lang.String getFriendNo();
    /**
     * <code>required string friendNo = 2;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getFriendNoBytes();

    // required string content = 3;
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code proto.ChatReq}
   */
  public static final class ChatReq extends
      com.google.protobuf.GeneratedMessage
      implements ChatReqOrBuilder {
    // Use ChatReq.newBuilder() to construct.
    private ChatReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatReq defaultInstance;
    public static ChatReq getDefaultInstance() {
      return defaultInstance;
    }

    public ChatReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userNo_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              friendNo_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.easy.ntprotocol.protobuf.ChatBuf.ChatReq.class, com.easy.ntprotocol.protobuf.ChatBuf.ChatReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatReq> PARSER =
        new com.google.protobuf.AbstractParser<ChatReq>() {
      public ChatReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userNo = 1;
    public static final int USERNO_FIELD_NUMBER = 1;
    private java.lang.Object userNo_;
    /**
     * <code>required string userNo = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public boolean hasUserNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userNo = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public java.lang.String getUserNo() {
      java.lang.Object ref = userNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userNo = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNoBytes() {
      java.lang.Object ref = userNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string friendNo = 2;
    public static final int FRIENDNO_FIELD_NUMBER = 2;
    private java.lang.Object friendNo_;
    /**
     * <code>required string friendNo = 2;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    public boolean hasFriendNo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string friendNo = 2;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    public java.lang.String getFriendNo() {
      java.lang.Object ref = friendNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          friendNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string friendNo = 2;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFriendNoBytes() {
      java.lang.Object ref = friendNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userNo_ = "";
      friendNo_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFriendNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserNoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFriendNoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserNoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFriendNoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.easy.ntprotocol.protobuf.ChatBuf.ChatReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ChatReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.easy.ntprotocol.protobuf.ChatBuf.ChatReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.easy.ntprotocol.protobuf.ChatBuf.ChatReq.class, com.easy.ntprotocol.protobuf.ChatBuf.ChatReq.Builder.class);
      }

      // Construct using com.easy.ntprotocol.protobuf.ChatBuf.ChatReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        friendNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatReq_descriptor;
      }

      public com.easy.ntprotocol.protobuf.ChatBuf.ChatReq getDefaultInstanceForType() {
        return com.easy.ntprotocol.protobuf.ChatBuf.ChatReq.getDefaultInstance();
      }

      public com.easy.ntprotocol.protobuf.ChatBuf.ChatReq build() {
        com.easy.ntprotocol.protobuf.ChatBuf.ChatReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.easy.ntprotocol.protobuf.ChatBuf.ChatReq buildPartial() {
        com.easy.ntprotocol.protobuf.ChatBuf.ChatReq result = new com.easy.ntprotocol.protobuf.ChatBuf.ChatReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userNo_ = userNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.friendNo_ = friendNo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.easy.ntprotocol.protobuf.ChatBuf.ChatReq) {
          return mergeFrom((com.easy.ntprotocol.protobuf.ChatBuf.ChatReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.easy.ntprotocol.protobuf.ChatBuf.ChatReq other) {
        if (other == com.easy.ntprotocol.protobuf.ChatBuf.ChatReq.getDefaultInstance()) return this;
        if (other.hasUserNo()) {
          bitField0_ |= 0x00000001;
          userNo_ = other.userNo_;
          onChanged();
        }
        if (other.hasFriendNo()) {
          bitField0_ |= 0x00000002;
          friendNo_ = other.friendNo_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserNo()) {
          
          return false;
        }
        if (!hasFriendNo()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.easy.ntprotocol.protobuf.ChatBuf.ChatReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.easy.ntprotocol.protobuf.ChatBuf.ChatReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userNo = 1;
      private java.lang.Object userNo_ = "";
      /**
       * <code>required string userNo = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public boolean hasUserNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userNo = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public java.lang.String getUserNo() {
        java.lang.Object ref = userNo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userNo = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNoBytes() {
        java.lang.Object ref = userNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userNo = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder setUserNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userNo = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder clearUserNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userNo_ = getDefaultInstance().getUserNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string userNo = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder setUserNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userNo_ = value;
        onChanged();
        return this;
      }

      // required string friendNo = 2;
      private java.lang.Object friendNo_ = "";
      /**
       * <code>required string friendNo = 2;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public boolean hasFriendNo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string friendNo = 2;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public java.lang.String getFriendNo() {
        java.lang.Object ref = friendNo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          friendNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string friendNo = 2;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFriendNoBytes() {
        java.lang.Object ref = friendNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string friendNo = 2;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public Builder setFriendNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        friendNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string friendNo = 2;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public Builder clearFriendNo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        friendNo_ = getDefaultInstance().getFriendNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string friendNo = 2;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public Builder setFriendNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        friendNo_ = value;
        onChanged();
        return this;
      }

      // required string content = 3;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.ChatReq)
    }

    static {
      defaultInstance = new ChatReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.ChatReq)
  }

  public interface ChatRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string friendNo = 1;
    /**
     * <code>required string friendNo = 1;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    boolean hasFriendNo();
    /**
     * <code>required string friendNo = 1;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    java.lang.String getFriendNo();
    /**
     * <code>required string friendNo = 1;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getFriendNoBytes();

    // required string content = 2;
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code proto.ChatResp}
   */
  public static final class ChatResp extends
      com.google.protobuf.GeneratedMessage
      implements ChatRespOrBuilder {
    // Use ChatResp.newBuilder() to construct.
    private ChatResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatResp defaultInstance;
    public static ChatResp getDefaultInstance() {
      return defaultInstance;
    }

    public ChatResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              friendNo_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.easy.ntprotocol.protobuf.ChatBuf.ChatResp.class, com.easy.ntprotocol.protobuf.ChatBuf.ChatResp.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatResp> PARSER =
        new com.google.protobuf.AbstractParser<ChatResp>() {
      public ChatResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string friendNo = 1;
    public static final int FRIENDNO_FIELD_NUMBER = 1;
    private java.lang.Object friendNo_;
    /**
     * <code>required string friendNo = 1;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    public boolean hasFriendNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string friendNo = 1;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    public java.lang.String getFriendNo() {
      java.lang.Object ref = friendNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          friendNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string friendNo = 1;</code>
     *
     * <pre>
     *好友账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFriendNoBytes() {
      java.lang.Object ref = friendNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.Object content_;
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      friendNo_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFriendNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFriendNoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFriendNoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.easy.ntprotocol.protobuf.ChatBuf.ChatResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ChatResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.easy.ntprotocol.protobuf.ChatBuf.ChatRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.easy.ntprotocol.protobuf.ChatBuf.ChatResp.class, com.easy.ntprotocol.protobuf.ChatBuf.ChatResp.Builder.class);
      }

      // Construct using com.easy.ntprotocol.protobuf.ChatBuf.ChatResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        friendNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.easy.ntprotocol.protobuf.ChatBuf.internal_static_proto_ChatResp_descriptor;
      }

      public com.easy.ntprotocol.protobuf.ChatBuf.ChatResp getDefaultInstanceForType() {
        return com.easy.ntprotocol.protobuf.ChatBuf.ChatResp.getDefaultInstance();
      }

      public com.easy.ntprotocol.protobuf.ChatBuf.ChatResp build() {
        com.easy.ntprotocol.protobuf.ChatBuf.ChatResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.easy.ntprotocol.protobuf.ChatBuf.ChatResp buildPartial() {
        com.easy.ntprotocol.protobuf.ChatBuf.ChatResp result = new com.easy.ntprotocol.protobuf.ChatBuf.ChatResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.friendNo_ = friendNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.easy.ntprotocol.protobuf.ChatBuf.ChatResp) {
          return mergeFrom((com.easy.ntprotocol.protobuf.ChatBuf.ChatResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.easy.ntprotocol.protobuf.ChatBuf.ChatResp other) {
        if (other == com.easy.ntprotocol.protobuf.ChatBuf.ChatResp.getDefaultInstance()) return this;
        if (other.hasFriendNo()) {
          bitField0_ |= 0x00000001;
          friendNo_ = other.friendNo_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFriendNo()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.easy.ntprotocol.protobuf.ChatBuf.ChatResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.easy.ntprotocol.protobuf.ChatBuf.ChatResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string friendNo = 1;
      private java.lang.Object friendNo_ = "";
      /**
       * <code>required string friendNo = 1;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public boolean hasFriendNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string friendNo = 1;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public java.lang.String getFriendNo() {
        java.lang.Object ref = friendNo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          friendNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string friendNo = 1;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFriendNoBytes() {
        java.lang.Object ref = friendNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string friendNo = 1;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public Builder setFriendNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        friendNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string friendNo = 1;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public Builder clearFriendNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        friendNo_ = getDefaultInstance().getFriendNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string friendNo = 1;</code>
       *
       * <pre>
       *好友账号
       * </pre>
       */
      public Builder setFriendNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        friendNo_ = value;
        onChanged();
        return this;
      }

      // required string content = 2;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.ChatResp)
    }

    static {
      defaultInstance = new ChatResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.ChatResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChatReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ChatReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChatResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ChatResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\005proto\"<\n\007ChatReq\022\016\n\006userNo" +
      "\030\001 \002(\t\022\020\n\010friendNo\030\002 \002(\t\022\017\n\007content\030\003 \002(" +
      "\t\"-\n\010ChatResp\022\020\n\010friendNo\030\001 \002(\t\022\017\n\007conte" +
      "nt\030\002 \002(\tB\'\n\034com.easy.ntprotocol.protobuf" +
      "B\007ChatBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_ChatReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_ChatReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ChatReq_descriptor,
              new java.lang.String[] { "UserNo", "FriendNo", "Content", });
          internal_static_proto_ChatResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_ChatResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ChatResp_descriptor,
              new java.lang.String[] { "FriendNo", "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
