// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connectNTHander.proto

package com.easy.ntprotocol.protobuf;

public final class ConnectNTHanderBuf {
  private ConnectNTHanderBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConnectNTHanderReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string no = 1;
    /**
     * <code>required string no = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    boolean hasNo();
    /**
     * <code>required string no = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    java.lang.String getNo();
    /**
     * <code>required string no = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    com.google.protobuf.ByteString
        getNoBytes();
  }
  /**
   * Protobuf type {@code proto.ConnectNTHanderReq}
   */
  public static final class ConnectNTHanderReq extends
      com.google.protobuf.GeneratedMessage
      implements ConnectNTHanderReqOrBuilder {
    // Use ConnectNTHanderReq.newBuilder() to construct.
    private ConnectNTHanderReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConnectNTHanderReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConnectNTHanderReq defaultInstance;
    public static ConnectNTHanderReq getDefaultInstance() {
      return defaultInstance;
    }

    public ConnectNTHanderReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConnectNTHanderReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              no_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.internal_static_proto_ConnectNTHanderReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.internal_static_proto_ConnectNTHanderReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq.class, com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ConnectNTHanderReq> PARSER =
        new com.google.protobuf.AbstractParser<ConnectNTHanderReq>() {
      public ConnectNTHanderReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConnectNTHanderReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectNTHanderReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string no = 1;
    public static final int NO_FIELD_NUMBER = 1;
    private java.lang.Object no_;
    /**
     * <code>required string no = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public boolean hasNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string no = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public java.lang.String getNo() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          no_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string no = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNoBytes() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        no_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      no_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ConnectNTHanderReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.internal_static_proto_ConnectNTHanderReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.internal_static_proto_ConnectNTHanderReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq.class, com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq.Builder.class);
      }

      // Construct using com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        no_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.internal_static_proto_ConnectNTHanderReq_descriptor;
      }

      public com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq getDefaultInstanceForType() {
        return com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq.getDefaultInstance();
      }

      public com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq build() {
        com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq buildPartial() {
        com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq result = new com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.no_ = no_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq) {
          return mergeFrom((com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq other) {
        if (other == com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq.getDefaultInstance()) return this;
        if (other.hasNo()) {
          bitField0_ |= 0x00000001;
          no_ = other.no_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.easy.ntprotocol.protobuf.ConnectNTHanderBuf.ConnectNTHanderReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string no = 1;
      private java.lang.Object no_ = "";
      /**
       * <code>required string no = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public boolean hasNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string no = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public java.lang.String getNo() {
        java.lang.Object ref = no_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          no_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string no = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNoBytes() {
        java.lang.Object ref = no_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          no_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string no = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder setNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        no_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string no = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder clearNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        no_ = getDefaultInstance().getNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string no = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder setNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        no_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.ConnectNTHanderReq)
    }

    static {
      defaultInstance = new ConnectNTHanderReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.ConnectNTHanderReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ConnectNTHanderReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ConnectNTHanderReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025connectNTHander.proto\022\005proto\" \n\022Connec" +
      "tNTHanderReq\022\n\n\002no\030\001 \002(\tB2\n\034com.easy.ntp" +
      "rotocol.protobufB\022ConnectNTHanderBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_ConnectNTHanderReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_ConnectNTHanderReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ConnectNTHanderReq_descriptor,
              new java.lang.String[] { "No", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
