// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.easy.ntprotocol.protobuf;

public final class LoginBuf {
  private LoginBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginSyncReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userKey = 1;
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    boolean hasUserKey();
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    java.lang.String getUserKey();
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserKeyBytes();

    // required string usrNo = 2;
    /**
     * <code>required string usrNo = 2;</code>
     *
     * <pre>
     *用户账号  
     * </pre>
     */
    boolean hasUsrNo();
    /**
     * <code>required string usrNo = 2;</code>
     *
     * <pre>
     *用户账号  
     * </pre>
     */
    java.lang.String getUsrNo();
    /**
     * <code>required string usrNo = 2;</code>
     *
     * <pre>
     *用户账号  
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsrNoBytes();
  }
  /**
   * Protobuf type {@code proto.LoginSyncReq}
   */
  public static final class LoginSyncReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginSyncReqOrBuilder {
    // Use LoginSyncReq.newBuilder() to construct.
    private LoginSyncReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginSyncReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginSyncReq defaultInstance;
    public static LoginSyncReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginSyncReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginSyncReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              usrNo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq.class, com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginSyncReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginSyncReq>() {
      public LoginSyncReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginSyncReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginSyncReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userKey = 1;
    public static final int USERKEY_FIELD_NUMBER = 1;
    private java.lang.Object userKey_;
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public boolean hasUserKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public java.lang.String getUserKey() {
      java.lang.Object ref = userKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserKeyBytes() {
      java.lang.Object ref = userKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string usrNo = 2;
    public static final int USRNO_FIELD_NUMBER = 2;
    private java.lang.Object usrNo_;
    /**
     * <code>required string usrNo = 2;</code>
     *
     * <pre>
     *用户账号  
     * </pre>
     */
    public boolean hasUsrNo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string usrNo = 2;</code>
     *
     * <pre>
     *用户账号  
     * </pre>
     */
    public java.lang.String getUsrNo() {
      java.lang.Object ref = usrNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usrNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string usrNo = 2;</code>
     *
     * <pre>
     *用户账号  
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsrNoBytes() {
      java.lang.Object ref = usrNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usrNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userKey_ = "";
      usrNo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsrNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUsrNoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUsrNoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.LoginSyncReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq.class, com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq.Builder.class);
      }

      // Construct using com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        usrNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncReq_descriptor;
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq getDefaultInstanceForType() {
        return com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq.getDefaultInstance();
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq build() {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq buildPartial() {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq result = new com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userKey_ = userKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.usrNo_ = usrNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq) {
          return mergeFrom((com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq other) {
        if (other == com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq.getDefaultInstance()) return this;
        if (other.hasUserKey()) {
          bitField0_ |= 0x00000001;
          userKey_ = other.userKey_;
          onChanged();
        }
        if (other.hasUsrNo()) {
          bitField0_ |= 0x00000002;
          usrNo_ = other.usrNo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserKey()) {
          
          return false;
        }
        if (!hasUsrNo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userKey = 1;
      private java.lang.Object userKey_ = "";
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public boolean hasUserKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public java.lang.String getUserKey() {
        java.lang.Object ref = userKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserKeyBytes() {
        java.lang.Object ref = userKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder setUserKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder clearUserKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userKey_ = getDefaultInstance().getUserKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder setUserKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userKey_ = value;
        onChanged();
        return this;
      }

      // required string usrNo = 2;
      private java.lang.Object usrNo_ = "";
      /**
       * <code>required string usrNo = 2;</code>
       *
       * <pre>
       *用户账号  
       * </pre>
       */
      public boolean hasUsrNo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string usrNo = 2;</code>
       *
       * <pre>
       *用户账号  
       * </pre>
       */
      public java.lang.String getUsrNo() {
        java.lang.Object ref = usrNo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          usrNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string usrNo = 2;</code>
       *
       * <pre>
       *用户账号  
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsrNoBytes() {
        java.lang.Object ref = usrNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usrNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string usrNo = 2;</code>
       *
       * <pre>
       *用户账号  
       * </pre>
       */
      public Builder setUsrNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        usrNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string usrNo = 2;</code>
       *
       * <pre>
       *用户账号  
       * </pre>
       */
      public Builder clearUsrNo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        usrNo_ = getDefaultInstance().getUsrNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string usrNo = 2;</code>
       *
       * <pre>
       *用户账号  
       * </pre>
       */
      public Builder setUsrNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        usrNo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.LoginSyncReq)
    }

    static {
      defaultInstance = new LoginSyncReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.LoginSyncReq)
  }

  public interface LoginSyncRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 ret = 1;
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *返回标识  
     * </pre>
     */
    boolean hasRet();
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *返回标识  
     * </pre>
     */
    int getRet();
  }
  /**
   * Protobuf type {@code proto.LoginSyncResp}
   */
  public static final class LoginSyncResp extends
      com.google.protobuf.GeneratedMessage
      implements LoginSyncRespOrBuilder {
    // Use LoginSyncResp.newBuilder() to construct.
    private LoginSyncResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginSyncResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginSyncResp defaultInstance;
    public static LoginSyncResp getDefaultInstance() {
      return defaultInstance;
    }

    public LoginSyncResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginSyncResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp.class, com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginSyncResp> PARSER =
        new com.google.protobuf.AbstractParser<LoginSyncResp>() {
      public LoginSyncResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginSyncResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginSyncResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 ret = 1;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *返回标识  
     * </pre>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *返回标识  
     * </pre>
     */
    public int getRet() {
      return ret_;
    }

    private void initFields() {
      ret_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ret_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ret_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.LoginSyncResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp.class, com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp.Builder.class);
      }

      // Construct using com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginSyncResp_descriptor;
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp getDefaultInstanceForType() {
        return com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp.getDefaultInstance();
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp build() {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp buildPartial() {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp result = new com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp) {
          return mergeFrom((com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp other) {
        if (other == com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.easy.ntprotocol.protobuf.LoginBuf.LoginSyncResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 ret = 1;
      private int ret_ ;
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *返回标识  
       * </pre>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *返回标识  
       * </pre>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *返回标识  
       * </pre>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *返回标识  
       * </pre>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.LoginSyncResp)
    }

    static {
      defaultInstance = new LoginSyncResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.LoginSyncResp)
  }

  public interface LoginConnReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userKey = 1;
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    boolean hasUserKey();
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    java.lang.String getUserKey();
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserKeyBytes();

    // required string userNo = 2;
    /**
     * <code>required string userNo = 2;</code>
     *
     * <pre>
     *用户账号
     * </pre>
     */
    boolean hasUserNo();
    /**
     * <code>required string userNo = 2;</code>
     *
     * <pre>
     *用户账号
     * </pre>
     */
    java.lang.String getUserNo();
    /**
     * <code>required string userNo = 2;</code>
     *
     * <pre>
     *用户账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNoBytes();
  }
  /**
   * Protobuf type {@code proto.LoginConnReq}
   */
  public static final class LoginConnReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginConnReqOrBuilder {
    // Use LoginConnReq.newBuilder() to construct.
    private LoginConnReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginConnReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginConnReq defaultInstance;
    public static LoginConnReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginConnReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginConnReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userNo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq.class, com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginConnReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginConnReq>() {
      public LoginConnReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginConnReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginConnReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userKey = 1;
    public static final int USERKEY_FIELD_NUMBER = 1;
    private java.lang.Object userKey_;
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public boolean hasUserKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public java.lang.String getUserKey() {
      java.lang.Object ref = userKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userKey = 1;</code>
     *
     * <pre>
     *用户KEY
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserKeyBytes() {
      java.lang.Object ref = userKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string userNo = 2;
    public static final int USERNO_FIELD_NUMBER = 2;
    private java.lang.Object userNo_;
    /**
     * <code>required string userNo = 2;</code>
     *
     * <pre>
     *用户账号
     * </pre>
     */
    public boolean hasUserNo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userNo = 2;</code>
     *
     * <pre>
     *用户账号
     * </pre>
     */
    public java.lang.String getUserNo() {
      java.lang.Object ref = userNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userNo = 2;</code>
     *
     * <pre>
     *用户账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNoBytes() {
      java.lang.Object ref = userNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userKey_ = "";
      userNo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserNoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserNoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.LoginConnReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq.class, com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq.Builder.class);
      }

      // Construct using com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnReq_descriptor;
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq getDefaultInstanceForType() {
        return com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq.getDefaultInstance();
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq build() {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq buildPartial() {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq result = new com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userKey_ = userKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userNo_ = userNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq) {
          return mergeFrom((com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq other) {
        if (other == com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq.getDefaultInstance()) return this;
        if (other.hasUserKey()) {
          bitField0_ |= 0x00000001;
          userKey_ = other.userKey_;
          onChanged();
        }
        if (other.hasUserNo()) {
          bitField0_ |= 0x00000002;
          userNo_ = other.userNo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserKey()) {
          
          return false;
        }
        if (!hasUserNo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.easy.ntprotocol.protobuf.LoginBuf.LoginConnReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userKey = 1;
      private java.lang.Object userKey_ = "";
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public boolean hasUserKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public java.lang.String getUserKey() {
        java.lang.Object ref = userKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserKeyBytes() {
        java.lang.Object ref = userKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder setUserKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder clearUserKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userKey_ = getDefaultInstance().getUserKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string userKey = 1;</code>
       *
       * <pre>
       *用户KEY
       * </pre>
       */
      public Builder setUserKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userKey_ = value;
        onChanged();
        return this;
      }

      // required string userNo = 2;
      private java.lang.Object userNo_ = "";
      /**
       * <code>required string userNo = 2;</code>
       *
       * <pre>
       *用户账号
       * </pre>
       */
      public boolean hasUserNo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userNo = 2;</code>
       *
       * <pre>
       *用户账号
       * </pre>
       */
      public java.lang.String getUserNo() {
        java.lang.Object ref = userNo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userNo = 2;</code>
       *
       * <pre>
       *用户账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNoBytes() {
        java.lang.Object ref = userNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userNo = 2;</code>
       *
       * <pre>
       *用户账号
       * </pre>
       */
      public Builder setUserNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userNo = 2;</code>
       *
       * <pre>
       *用户账号
       * </pre>
       */
      public Builder clearUserNo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userNo_ = getDefaultInstance().getUserNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string userNo = 2;</code>
       *
       * <pre>
       *用户账号
       * </pre>
       */
      public Builder setUserNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userNo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.LoginConnReq)
    }

    static {
      defaultInstance = new LoginConnReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.LoginConnReq)
  }

  public interface LoginConnRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 ret = 1;
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *返回标识  
     * </pre>
     */
    boolean hasRet();
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *返回标识  
     * </pre>
     */
    int getRet();
  }
  /**
   * Protobuf type {@code proto.LoginConnResp}
   */
  public static final class LoginConnResp extends
      com.google.protobuf.GeneratedMessage
      implements LoginConnRespOrBuilder {
    // Use LoginConnResp.newBuilder() to construct.
    private LoginConnResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginConnResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginConnResp defaultInstance;
    public static LoginConnResp getDefaultInstance() {
      return defaultInstance;
    }

    public LoginConnResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginConnResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp.class, com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginConnResp> PARSER =
        new com.google.protobuf.AbstractParser<LoginConnResp>() {
      public LoginConnResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginConnResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginConnResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 ret = 1;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *返回标识  
     * </pre>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ret = 1;</code>
     *
     * <pre>
     *返回标识  
     * </pre>
     */
    public int getRet() {
      return ret_;
    }

    private void initFields() {
      ret_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ret_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ret_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.LoginConnResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.easy.ntprotocol.protobuf.LoginBuf.LoginConnRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp.class, com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp.Builder.class);
      }

      // Construct using com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.easy.ntprotocol.protobuf.LoginBuf.internal_static_proto_LoginConnResp_descriptor;
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp getDefaultInstanceForType() {
        return com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp.getDefaultInstance();
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp build() {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp buildPartial() {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp result = new com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp) {
          return mergeFrom((com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp other) {
        if (other == com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.easy.ntprotocol.protobuf.LoginBuf.LoginConnResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 ret = 1;
      private int ret_ ;
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *返回标识  
       * </pre>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *返回标识  
       * </pre>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *返回标识  
       * </pre>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ret = 1;</code>
       *
       * <pre>
       *返回标识  
       * </pre>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.LoginConnResp)
    }

    static {
      defaultInstance = new LoginConnResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.LoginConnResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LoginSyncReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LoginSyncReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LoginSyncResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LoginSyncResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LoginConnReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LoginConnReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LoginConnResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LoginConnResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\022\005proto\".\n\014LoginSyncReq\022\017\n\007" +
      "userKey\030\001 \002(\t\022\r\n\005usrNo\030\002 \002(\t\"\034\n\rLoginSyn" +
      "cResp\022\013\n\003ret\030\001 \002(\005\"/\n\014LoginConnReq\022\017\n\007us" +
      "erKey\030\001 \002(\t\022\016\n\006userNo\030\002 \002(\t\"\034\n\rLoginConn" +
      "Resp\022\013\n\003ret\030\001 \002(\005B(\n\034com.easy.ntprotocol" +
      ".protobufB\010LoginBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_LoginSyncReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_LoginSyncReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_LoginSyncReq_descriptor,
              new java.lang.String[] { "UserKey", "UsrNo", });
          internal_static_proto_LoginSyncResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_LoginSyncResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_LoginSyncResp_descriptor,
              new java.lang.String[] { "Ret", });
          internal_static_proto_LoginConnReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_proto_LoginConnReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_LoginConnReq_descriptor,
              new java.lang.String[] { "UserKey", "UserNo", });
          internal_static_proto_LoginConnResp_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_proto_LoginConnResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_LoginConnResp_descriptor,
              new java.lang.String[] { "Ret", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
